CREATE TABLE visitor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_key UUID NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('TEST', 'GAME', 'WORLD_CUP', 'ICEBREAKER')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE content_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL REFERENCES content(id),
    version_no VARCHAR(40) NOT NULL,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (content_id, version_no),
    UNIQUE (id, content_id)
);

CREATE INDEX idx_content_version_published
    ON content_version(content_id, published_at DESC)
    WHERE published_at IS NOT NULL;

CREATE TABLE content_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL REFERENCES content_version(id),
    code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    sort_order INTEGER NOT NULL CHECK (sort_order >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (version_id, code),
    UNIQUE (id, version_id)
);

CREATE TABLE share_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL REFERENCES content(id),
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CHECK (char_length(code) >= 6)
);

CREATE INDEX idx_share_link_content ON share_link(content_id);

CREATE TABLE visit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id BIGINT NOT NULL REFERENCES visitor(id),
    visit_key UUID NOT NULL UNIQUE,
    share_link_id BIGINT REFERENCES share_link(id),
    started_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_visit_visitor_started ON visit(visitor_id, started_at DESC);
CREATE INDEX idx_visit_started ON visit(started_at);
CREATE INDEX idx_visit_share_link ON visit(share_link_id) WHERE share_link_id IS NOT NULL;

CREATE TABLE participation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT NOT NULL REFERENCES visit(id),
    version_id BIGINT NOT NULL REFERENCES content_version(id),
    result_id BIGINT,
    request_key UUID NOT NULL UNIQUE,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    FOREIGN KEY (result_id, version_id) REFERENCES content_result(id, version_id),
    CHECK (result_id IS NULL OR completed_at IS NOT NULL)
);

CREATE INDEX idx_participation_version_started ON participation(version_id, started_at);
CREATE INDEX idx_participation_visit ON participation(visit_id);
CREATE INDEX idx_participation_result ON participation(result_id) WHERE result_id IS NOT NULL;
CREATE INDEX idx_participation_completed ON participation(completed_at) WHERE completed_at IS NOT NULL;

CREATE TABLE content_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id BIGINT NOT NULL REFERENCES visitor(id),
    content_id BIGINT NOT NULL REFERENCES content(id),
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (visitor_id, content_id)
);

CREATE INDEX idx_content_like_content ON content_like(content_id);

CREATE TABLE event_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key UUID NOT NULL UNIQUE,
    visit_id BIGINT NOT NULL REFERENCES visit(id),
    content_id BIGINT REFERENCES content(id),
    event_type VARCHAR(24) NOT NULL CHECK (event_type IN ('PAGE_VIEW', 'CONTENT_VIEW', 'SHARE_CLICK')),
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    CHECK (jsonb_typeof(data) = 'object')
);

CREATE INDEX idx_event_log_content_type_created ON event_log(content_id, event_type, created_at);
CREATE INDEX idx_event_log_created ON event_log(created_at);
CREATE INDEX idx_event_log_visit ON event_log(visit_id);

INSERT INTO content (code, name, type, status, created_at, updated_at) VALUES
    ('heart-trace', '마음속 흔적 찾기', 'TEST', 'PUBLISHED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('balance-game', '극과 극 밸런스 게임', 'GAME', 'PUBLISHED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ideal-world-cup', '최애 월드컵', 'WORLD_CUP', 'PUBLISHED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('group-picker', '오늘은 누구?', 'ICEBREAKER', 'PUBLISHED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('anonymous-sharing', '익명으로 만나는 우리', 'ICEBREAKER', 'PUBLISHED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('gureumi', '구르미 테스트', 'TEST', 'DRAFT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO content_version (content_id, version_no, published_at, created_at)
SELECT id, 'v1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM content
WHERE status = 'PUBLISHED';

INSERT INTO content_version (content_id, version_no, published_at, created_at)
SELECT id, 'v0-preview', NULL, CURRENT_TIMESTAMP
FROM content
WHERE code = 'gureumi';

INSERT INTO content_result (version_id, code, name, sort_order, active, created_at)
SELECT version.id, seed.code, seed.name, seed.sort_order, TRUE, CURRENT_TIMESTAMP
FROM content_version version
JOIN content ON content.id = version.content_id
CROSS JOIN (VALUES
    ('bear', '곰곰이', 1),
    ('spring', '봄봄이', 2),
    ('effort', '낑낑이', 3),
    ('pause', '숨숨이', 4),
    ('express', '톡톡이', 5)
) AS seed(code, name, sort_order)
WHERE content.code = 'heart-trace' AND version.version_no = 'v1';
